### PR TITLE
Fix the debug print

### PR DESCRIPTION
**Pull request by jockebech**
Resolves issue: https://bugs.linaro.org/show_bug.cgi?id=2360

Signed-off-by: Joakim Bech joakim.bech@linaro.org

### CODE REVIEW

**Comment by vchong** [comment]
Should we rename the script to build_ta_helloworld_qemu.sh or something like that so that people won't try to use it on hikey or another platform. OTOH, the binary will run anyway since the code's generic (assuming 64-bit NSU also supports 32-bit executables)?

With or without comment addressed:
`Reviewed-by: Victor Chong <victor.chong@linaro.org>`

**Comment by jbech-linaro** [comment]
Fine with me Victor, I'll update, but like I said in the bugzilla ticket above, I think it would be good if people stopped using this.

**Comment by vchong** [comment]
From what I can see, I think that for many users, after they're done running a full build based on the manifest and xtest to make sure everything's ok, they actually turn back to this hello world example to I guess start learning about TA basics. It's also good introductory material for training, along with the gp_conf stuffs. : )

**Comment by jbech-linaro** [comment]
I don't have anything against a single stand alone **maintained** TA, that resides at for example linaro-swg. A half a year ago I started this: https://github.com/jbech-linaro/template_ta with the intention that it should be moved to linaro-swg and be included in our repo manifest also.

**Comment by vchong** [comment]
Ok. I'll try to move people away from this and direct them to https://github.com/linaro-swg/template_ta instead in the future. Maybe we should put a notice/redirect here for that as well?

**Comment by jbech-linaro** [comment]
@vchong , well, that template-ta is just like this TA, i.e., "non-maintained" and not in linaro-swg. So that would just be same same but different. If you would like to help out here and find some time for it, then please try to put a simple TA at linaro-swg **and** include it in our manifest files. If it's the "hello world", "template TA" or something else doesn't really matter. Clean and simple and included in official builds, that's what I'm striving for.

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jbech-linaro** [comment]
Squashed and tags applied.
@kuscsik, it might be worth pulling this into your fork also as of now, since David is referring to your fork in his [AOSP setup](https://github.com/linaro-swg/optee_android_manifest/blob/master/optee.xml#L21) (I'll have a chat with David, how to deal with this in the future, change base repo, remove it or something like that).

**Comment by vchong** [comment]
@jbech-linaro Ok. I'll look into it as soon as I get a chance.

**Pull request merged**
